#!/bin/bash

set -e

notify title "QUESTION: Pre-installation starts ..."

# copy schema and add to metadata
cp -f /scripts/setup/question.json ${LCS_HOME}/schema/question.json
lcs-bt --append question

# complete
notify title "QUESTION: Image installation completed."
